### PR TITLE
Support for opening roms from launchers

### PR DESCRIPTION
**Pull request by DiegoBM**
Hi @SSimco, first of all thank you for your astounding work porting Cemu to android!

This PR is something that I put together quickly since I wanted to be able to externally open roms, from the file explorer as well as from launchers like "Daijisho" and "Es-De", which this makes possible.

You might decide to go a totally different way in terms of externally opening roms, in which case please feel free to close this PR.

Thank you again for your hard work.

Regards

### CODE REVIEW

**Comment by SSimco** [comment]
I'll try to refactor the existing code to use the launch paths instead of title Ids for starting the games and add the option to open games from file managers.

**Comment by SSimco** [comment]
Implemented in 80ea25b10f9ca33f88d4d7f2dbfb03ef9168ba46

**Comment by DiegoBM** [comment]
I tried building it but unfortuntely didn't work for me, neither from file manager (HyperOS native and File manager plus), nor any launcher. It seems like the application is not registering itself to open files and hence can't be found. Maybe I'm doing something wrong, I did clean the project and build again, I might try again tomorrow from a fresh clone.

**Comment by SSimco** [comment]
You can try a build from the release page https://github.com/SSimco/Cemu/releases/tag/ab53e98

**Comment by DiegoBM** [comment]
Thank you for the release! I tried, and the Launchers now picked it up (although Daijisho fails to open, maybe related to the URL encoded path?), but same results for file managers, it's not coming up in the "Open With" option. For the sake of being extra thorough I also tried with "FV file manager", with no success

**Comment by SSimco** [comment]
> Thank you for the release! I tried, and the Launchers now picked it up (although Daijisho fails to open, maybe related to the URL encoded path?), but same results for file managers, it's not coming up in the "Open With" option. For the sake of being extra thorough I also tried with "FV file manager", with no success

Can you try again with Daijisho with this release? https://github.com/SSimco/Cemu/releases/tag/32795e1
I think the issue was as you said, the URL were not encoded correctly. It should be fixed by now.

**Comment by DiegoBM** [comment]
Daijisho is loving the new release (so am I). Launcher-approved! I still need to figure out why file managers are not detecting cemu as an open option though, it worked fine with the oversimplified intent in my PR, maybe it's now too specific?

**Pull request closed without merging**
